### ISSUE TITLE
Drag'n'drop not working on Firefox

### ISSUE THREAD

**Issue by raimohanska** [raimohanska/r-board#1]
Stickies go to top-left.

**Comment by raimohanska** [comment]
Works on my Chrome.

**Comment by raimohanska** [comment]
On Safari, stickies move but with a delay and by too great increments.
On iOS Safari, stickies don't move.

**Comment by jrasanen** [comment]
This thread had a workaround [in this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=505521#c82)

**Comment by raimohanska** [comment]
Unfortunately the fix

**Comment by raimohanska** [comment]
I split touchscreen support into #2

**Comment by raimohanska** [comment]
Automatic deploys to Heroku enabled now.

**Comment by raimohanska** [comment]
It seems the y coordinate gets out of whack with Chrome with this fix. With Safari I get yet another kind of wrong behavior. Who knew this was so hard.

**Comment by raimohanska** [comment]
I introduced some really ugly code that seems to fix the coordinates issue :)

**Comment by raimohanska** [comment]
... and more to have new postits appear on the right spot.

Safari still has some nasty animation delay and doesn't show the little new postits while dragging.

**Comment by raimohanska** [comment]
Safari slow animation disabled.

**Comment by raimohanska** [comment]
Desktop browser issues seem fixed. The code is really nasty at the moment. Sprinkle some abstraction powder.
