### ISSUE TITLE
Free form notes

### ISSUE THREAD

**Issue by tkurki** [raimohanska/r-board#150]
There are cases where a note
- should have really long lines that you'd prefer not wrapped
- as they would be much more readable on several lines, as a list like this here
- not constrainted by squares would allow also more freeform expression

Or is it just me not finding how the aspect ratio can be changed?

**Comment by tkurki** [comment]
![image](https://user-images.githubusercontent.com/1049678/111024519-dd650000-83e7-11eb-852d-014e222b3b0d.png)

![image](https://user-images.githubusercontent.com/1049678/111024597-49dfff00-83e8-11eb-9101-dae917e4704f.png)

**Comment by raimohanska** [comment]
You can use the Text element instead on Notes

**Comment by raimohanska** [comment]
https://www.ourboard.io/b/92735904-c431-49d7-b5d7-5d99c80b0d19
