### ISSUE TITLE
Locks problem with container paste

### ISSUE THREAD

**Issue by raimohanska** [raimohanska/r-board#36]
After pasting a container with children, the locks thing causes all of the contained elements to be in focus, while only the container should be. Without locks it behaves correctly.

**Comment by jussisaurio** [comment]
can you still repro?

**Comment by jussisaurio** [comment]
I can't, so closing. Fixed in https://github.com/raimohanska/r-board/commit/d21cc4cd09787b5d22d3fd62113d74e73b92103b
