### ISSUE TITLE
Last character inputted to text field (sometimes) does not get sent as item.update to server

### ISSUE THREAD

**Issue by jussisaurio** [raimohanska/r-board#46]
Reproduced this manually, but it seems like Cypress tests sometimes flake for the same reason as well, e.g. expected to find text "HELLO" but found "HELL" instead

Web development is HELL

**Comment by raimohanska** [comment]
Easy to reproduce by slowing down server acks like `setTimeout(() => ackFn?.("ack"), 500)` and then just typing quickly "asdf" on a note. On the client side it seems that the latest texts are enqueued but never sent. Indicates a bug in message-queue.

Did not have time to find out what actually happens in message-queue, resulting to not sending the latest events.
