### ISSUE TITLE
App starts up way slower on Firefox than Chrome

### ISSUE THREAD

**Issue by jussisaurio** [raimohanska/r-board#50]
Repro both on Heroku and locally. Seems like it's stuck waiting for messages from socket.io for a few seconds. Happens systematically.

**Comment by jussisaurio** [comment]
running with DEBUG=engine

engine intercepting request for path "/socket.io/" +5s

**Comment by jussisaurio** [comment]
socket.io-parser decoded 21["message","app-event",{"action":"cursor.move","position":{"x":0,"y":0},"boardId":"default"}] as {"type":2,"nsp":"/","id":1,"data":["message","app-event",{"action":"cursor.move","position":{"x":0,"y":0},"boardId":"default"}]} **+5s**

**Comment by jussisaurio** [comment]
Actually, I went back and tried it on Heroku, and it seems like **this only happens on localhost**. It's still slower on Firefox, but not so much that it degrades quality of life I guess.

Related:

https://bugzilla.mozilla.org/show_bug.cgi?id=1662694

**Comment by raimohanska** [comment]
I find performance on Firefox acceptable. Is there something to investigate or just close?
