### ISSUE TITLE
Cannot start drag-to-multiselect from within container

### ISSUE THREAD

**Issue by jussisaurio** [raimohanska/r-board#55]
Would be useful to be able to drag-select items inside a container, but for that you have to start the drag outside the container

Perhaps containers should have a special handle for dragging

**Comment by raimohanska** [comment]
One way to get around this could be implementing Locking for containers (#56) but being able to do drag-select without having to lock first would be nicer still. If we look how Mural does this, they seem to have a ~10px draggable border in containers, and if you drag nearer the center, it will not result to selection of the container but drag-select instead. This might be good.

**Comment by jussisaurio** [comment]
implemented draggable borders in https://github.com/raimohanska/r-board/commit/ddd3e9eeb1434f3c235e43b8e7b97dd5f197d584

**Comment by raimohanska** [comment]
When you drag-select within a container, the container itself should not be selected. Otherwise you cannot effectively do anything useful with the selection. If the container is selected too, you cannot move/delete the items within without moving/deleting the container too.

**Comment by jussisaurio** [comment]
ok now?

**Comment by raimohanska** [comment]
Very nice!
