### ISSUE TITLE
Idea: Optimize image dragging by trying fetch first

### ISSUE THREAD

**Issue by raimohanska** [raimohanska/r-board#57]
In 739f0aa04a8a41060e9163ba9070ed7af86b1c34 image dragging from the Web was changed to always use the r-board server as a middleman, to bypass CORS problems. We could further optimize by using `fetch` first and resorting to serverside trip only if CORS fails.

**Comment by jussisaurio** [comment]
implemented with minimal logic at https://github.com/raimohanska/r-board/commit/9df8ab39dfb7ecc562adcd6f430fc039a6b55a59
