### ISSUE TITLE
Copy-paste

### ISSUE THREAD

**Issue by raimohanska** [raimohanska/r-board#9]
Copy and paste the selected elements. The pasted elements become the new selected elements.

Selection mechanism as well as moving / resizing already exists.

**Comment by jussisaurio** [comment]
Functionality added in https://github.com/raimohanska/r-board/commit/9c92b8959c4b7c7a0b93ac04d99271d3773f0cfc

Tests are not written so not closing

**Comment by jussisaurio** [comment]
Also, pasted elements do not become selected elements

AND

they are currently always pasted to the exact location where they were copied from

**Comment by jussisaurio** [comment]
Completed with https://github.com/raimohanska/r-board/commit/95e4872bb1d1662ec47ab5b928595caa729b2003
