### ISSUE TITLE
Support panning across the board by pressing space and dragging

### ISSUE THREAD

**Issue by googol** [raimohanska/r-board#95]

**Comment by raimohanska** [comment]
Can you elaborate?

**Comment by googol** [comment]
Many design tools allow you to drag the board itself around when you press space while you drag the mouse, instead of interacting with the objects on the board. It would be a lot nicer than using the scrollbars for scrolling on a large board

**Comment by raimohanska** [comment]
Hmm... Isn't two-finger scroll used for that? Not saying that it would be hard to implement this.

**Comment by raimohanska** [comment]
heh, we all live in our bubbles, I see :) would you care to make a PR at some point?

**Comment by googol** [comment]
Im just looking into it actually

**Comment by raimohanska** [comment]
We now have "pan" and "select" tools in the menu.
